//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Info
    {
        public Bill_Info()
        {
            this.DetailBill_Info = new HashSet<DetailBill_Info>();
        }
    
        public string BILLID { get; set; }
        public string PATIENTID { get; set; }
        public string USERID { get; set; }
        public System.DateTime BILLDATE { get; set; }
        public double BILLCOST { get; set; }
        public string DEPARTMENTID { get; set; }
        public bool BILLSTATUS { get; set; }
        public string SERVICEGROUPID { get; set; }
    
        public virtual Patient_Info Patient_Info { get; set; }
        public virtual ServiceGroup_Info ServiceGroup_Info { get; set; }
        public virtual User_Info User_Info { get; set; }
        public virtual ICollection<DetailBill_Info> DetailBill_Info { get; set; }
    }
}
