//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentType_Info
    {
        public DepartmentType_Info()
        {
            this.Department_Info = new HashSet<Department_Info>();
        }
    
        public string DEPARTMENTTYPEID { get; set; }
        public string DEPARTMENTTYPENAME { get; set; }
        public string DEPARTMENTTYPEDESCRIPTION { get; set; }
        public bool DEPARTMENTSTATUS { get; set; }
    
        public virtual ICollection<Department_Info> Department_Info { get; set; }
    }
}
