//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class District_Info
    {
        public string DISTRICTID { get; set; }
        public string CITYID { get; set; }
        public string DISTRICTNAME { get; set; }
        public string DISTRICTDESCRIPTION { get; set; }
        public bool DISTRICTSTATUS { get; set; }
    
        public virtual City_Info City_Info { get; set; }
    }
}
