//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Info
    {
        public Patient_Info()
        {
            this.Bill_Info = new HashSet<Bill_Info>();
        }
    
        public string PATIENTID { get; set; }
        public string PATIENTNAME { get; set; }
        public int GENDER { get; set; }
        public string ADDRESS { get; set; }
        public string PATIENTPHONE { get; set; }
        public System.DateTime DATEOFBIRTH { get; set; }
    
        public virtual ICollection<Bill_Info> Bill_Info { get; set; }
    }
}
