//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill_Info
    {
        public int DETAILBILLID { get; set; }
        public string SERVICEID { get; set; }
        public double SERVICECOST { get; set; }
        public string BILLID { get; set; }
    
        public virtual Bill_Info Bill_Info { get; set; }
        public virtual Service_Info Service_Info { get; set; }
    }
}
