//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Info
    {
        public Service_Info()
        {
            this.DetailBill_Info = new HashSet<DetailBill_Info>();
        }
    
        public string SERVICEID { get; set; }
        public string SERVICEGROUPID { get; set; }
        public string SERVICENAME { get; set; }
        public string SERVICEDESCRIPTION { get; set; }
        public double SERVICECOST { get; set; }
        public bool SERVICESTATUS { get; set; }
    
        public virtual ICollection<DetailBill_Info> DetailBill_Info { get; set; }
        public virtual ServiceGroup_Info ServiceGroup_Info { get; set; }
    }
}
