//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceGroup_Info
    {
        public ServiceGroup_Info()
        {
            this.Bill_Info = new HashSet<Bill_Info>();
            this.Service_Info = new HashSet<Service_Info>();
        }
    
        public string SERVICEGROUPID { get; set; }
        public string SERVICEGROUPNAME { get; set; }
        public string SERVICEBROUPDESCRIPTION { get; set; }
        public bool SERVICEGROUPSTATUS { get; set; }
    
        public virtual ICollection<Bill_Info> Bill_Info { get; set; }
        public virtual ICollection<Service_Info> Service_Info { get; set; }
    }
}
