//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType_Info
    {
        public UserType_Info()
        {
            this.User_Info = new HashSet<User_Info>();
        }
    
        public string USERTYPEID { get; set; }
        public string USERTYPENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string AUTHORUZATION { get; set; }
        public bool USERTYPESTATUS { get; set; }
    
        public virtual ICollection<User_Info> User_Info { get; set; }
    }
}
